name = "clashmarket-router"
main = "index.ts"
compatibility_date = "2024-12-16"

routes = [
  { pattern = "clashmarket.online/*", zone_name = "clashmarket.online" },
  { pattern = "www.clashmarket.online/*", zone_name = "clashmarket.online" }
]